# Generated by Django 2.2.16 on 2022-05-13 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_confirmation_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='confirmation',
            old_name='user',
            new_name='username',
        ),
    ]
