# Generated by Django 2.2.16 on 2022-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220514_0050'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='confirmation_code',
            field=models.TextField(default=12345),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Confirmation',
        ),
    ]
