# Generated by Django 2.2.16 on 2022-05-18 14:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_title_score'),
        ('reviews', '0002_auto_20220517_2040'),
    ]

    operations = [
    ]
